### ISSUE TITLE
Python Version Error

### ISSUE THREAD

**Issue by Rathvire** [sourcery-ai/sourcery-vscode#101]
Hey, Sourcery throws this error on vscode start. Also mentions something about int not having a split method. 

This may be due to some personal ignorance on my part but I've been unable to find anything mentioning this specific error thus far.
Using the schema at https://docs.sourcery.ai/resources/sourcery_yaml_schema.json

Sourcery version 0.12.11, Occurs on other versions also. 
vscode version 1.72.2

.sourcery.yaml config in question
python_version: '3.6'

throws the below
Incorrect type. Expected "PythonVersion".
![Sourcery Bug](https://user-images.githubusercontent.com/110319095/197370669-69ae3f0d-b394-4c75-93d0-303d68c152d2.png)

**Comment by brendanator** [comment]
Thank you for reporting this @Rathvire 

This appears to be a problem with our schema and it won't affect the running of our application. You have configured it correctly as a string.

We will fix our schema so this doesn't occur

**Comment by Rathvire** [comment]
Thanks
