### ISSUE TITLE
when clicking "Sourcery" in the status line, a NOENT error is thrown, cannot find file (sourcery issue #297)

### ISSUE THREAD

**Issue by gargolito** [sourcery-ai/sourcery-vscode#103]
**Note:** I had opened issue [**297**](https://github.com/sourcery-ai/sourcery/issues/297) in the sourcery repo, but it seems like it should be here instead.

### Checklist

- [X] I have searched the [Sourcery documentation](https://docs.sourcery.ai/) for the issue, and found nothing
- [X] I have checked there are no open [bugs](https://github.com/sourcery-ai/sourcery/issues?q=label%3Abug) referencing the same bug or problem

### Description

When you click on "Sourcery" in the status bar, I get the message: a
`A system error occurred (ENOENT: no such file or directory, open '/home/{USER}/.vscode/extensions/sourcery.sourcery-0.12.12/assets/hubContainer.html')`

The **_.../assets_** sub-directory doesn't exist in my systems.

**Note:** I removed and reinstalled the extension to try and resolve the issue.

### Code snippet that reproduces issue

**N/A**

### Debug Information

IDE Version: 

VS Code 1.72.2

Sourcery Version: 

Sourcery 0.12.12

Operating system and Version:

Kubuntu Linux 22.04 and Pop!OS 2.04

**Comment by ruancomelli** [comment]
As mentioned in https://github.com/sourcery-ai/sourcery/issues/297, a fix for this issue has already been merged and will be available in the next Sourcery release.

Thank you for reporting this issue!

I added the `next release` label to this issue and will keep it open until the next release goes live.

**Comment by Hellebore** [comment]
Now released.
