### ISSUE TITLE
Scan only open files

### ISSUE THREAD

**Issue by Thalos12** [sourcery-ai/sourcery-vscode#11]
I would like the extension to show suggestions only for open files.

Currently, the suggestions appear as soon as I open a file, but when I close it they remain in the "Problems" tab.
If possible, I would like them to automatically go away when I close the file to avoid clutter.

**Comment by Hellebore** [comment]
Hi - thanks for the suggestion. 

We're going to be working on the UX in the next few weeks so will definitely consider this for inclusion.

**Comment by Thalos12** [comment]
That's great news, thank you very much.
I am looking forward to seeing this feature added.

**Comment by Hellebore** [comment]
This has now been added in as a feature in the latest extension version.
