### ISSUE TITLE
Enabling Sourcery conflicts with pylance 

### ISSUE THREAD

**Issue by Josverl** [sourcery-ai/sourcery-vscode#121]
I have found in multiple project that pylance and mypy warnings are suppressed after installing/enabling sourcery.
I have also seen that after a few on/off toggles they can work together, sometimes.
This also makes it hard to provide a repro here 

**_Speculation:_**
It seems that soucery clears the list of problems , including all raised by other tools
thus the actual problems shown , depends on the execution order of the tools. Last writer wins. ( and as pylance is more often faster than sourcery , this results in hiding errors.

## Pylance + mypy + sourcery enabled 

Only sourcery messages 

![image](https://user-images.githubusercontent.com/981654/215106242-f50aefd7-1119-4281-a4a0-8f74b07167eb.png)

 * Disable Sourcery 
 * > Developer: reload window

![image](https://user-images.githubusercontent.com/981654/215107472-25889d06-18b6-4a75-b98d-327f43ee6f83.png)

 * re-enable sourcery 
 * Save file 

![image](https://user-images.githubusercontent.com/981654/215107792-a7ee6428-95e4-4f2e-9e11-dcfd6eafb5aa.png)

**Comment by Hellebore** [comment]
This is rather strange - I'm fairly sure extensions can't interfere with each other in this way (and can't see anything in the vscode documentation or issues about it). 

Sourcery acts as an LSP server, sending its diagnostics which vs code adds to the problem pane. Pretty sure we don't interact with it directly.

Are these errors from overlapping ranges in the code?

**Comment by Hellebore** [comment]
Haven't been able to reproduce this locally - do you see the errors from pylance pop up and disappear, or do they never appear? 

We don't have logging that would help with this - but looks like you can enable something in pylance that might shed some more light
```to enable tracing add this to your settings.json
"python.analysis.logLevel": "Trace",```

(from
https://github.com/microsoft/pylance-release/issues/262)

**Comment by Josverl** [comment]
'sometimes' i notice that there are no errors shown by pylance, when there are obvious problems.
in thos case allways Source is showing some issues. 
If I restart VSCOde , pylance shows the issues , then Source presents the results , but removes Pylances messages ( sourcery is often a few seconds later than pylance )

Il try tracing in pylance, but without any logging on the sourcery side I do not have my hopes up

**Comment by Hellebore** [comment]
@Josverl This is now live with version 1.0.6 - could you please test it out and see if the change had any effect?
