### ISSUE TITLE
sourcery.sourcery not compatible with VS Code version 1.40.2

### ISSUE THREAD

**Issue by irahorecka** [sourcery-ai/sourcery-vscode#14]
Hi there, I am attempting to download the Sourcery plugin for VS Code (version 1.40.2, MacOS 10.15.4) from the VS Code marketplace and am getting an incompatible error. I am wondering if there is an alternative way to download Sourcery?

**Comment by brendanator** [comment]
The current minimum version of VSCode is 1.41 which is from November last year. I've investigated and it doesn't look like there's any issue with supporting earlier versions. The next version of the `sourcery.sourcery` extension will be compatible with 1.30.0 and above

**Comment by Hellebore** [comment]
Fixed with release 0.2.5 of vscode extension.
