### ISSUE TITLE
Provide more options for installation of the VSCode extension

### ISSUE THREAD

**Issue by brendanator** [sourcery-ai/sourcery-vscode#17]
I use [VSCodium](https://vscodium.com/), which pulls extensions from [open-vsx.org](https://open-vsx.org), so it would be great to have the extension there. 

It is also helpful to be able to download the .vsix and install manually

**Comment by Hellebore** [comment]
Sourcery is now uploaded to open-vsx.org - have just checked and it works on gitpod as well.
