### ISSUE TITLE
Very slow extension activation time

### ISSUE THREAD

**Issue by xshapira** [sourcery-ai/sourcery-vscode#171]
In the past few days, I have noticed a very slow activation time of Sourcery—`1370ms`.

<img width="1428" alt="CleanShot 2023-06-22 at 19 37 26@2x" src="https://github.com/sourcery-ai/sourcery-vscode/assets/48856190/9499d95d-9cd0-4b6e-be0e-cae1676202bc">

**Comment by reka** [comment]
Thanks a lot for reporting this. :+1:  It's very slow indeed.

Can you give some info about your system?

* OS
* VSCode version

Does this lead to a noticeable delay or hanging? Or is this long activation time visible only on the "Running Extensions" tab?

**Comment by xshapira** [comment]
- macOS Monterey 12.6.5
- VS Code Version: 1.79.2

I haven't seen any big slowdowns, but I'm sure it impacts some places.

**Comment by cpoptic** [comment]
+1 If you run `Developer: Show Running Extensions` in the VS Code command palette, Sourcery 1.4.0 is (by far) the longest loading VS Code extension.   Mine is showing 8212 ms!  8.2 seconds.  For comparison, Pylance is only 1135 ms.
How can we reduce the extension loading time?

**Comment by Hellebore** [comment]
Am looking into addressing this.

**Comment by Hellebore** [comment]
@cpoptic @xshapira could you please install the latest version (1.5.0) and check the activation time? Want to make sure we've addressed the issue.

**Comment by xshapira** [comment]
Fixed. Great job guys! 

![CleanShot 2023-06-30 at 11 04 38@2x](https://github.com/sourcery-ai/sourcery-vscode/assets/48856190/a28a0d51-2736-4d38-a783-efa8ec509be6)
