### ISSUE TITLE
Don't store the token for the VSCode extension in settings.json

### ISSUE THREAD

**Issue by brendanator** [sourcery-ai/sourcery-vscode#18]
Many people store their settings.json in public GitHub repos or Gists.

I would suggest storing the token in the VSCode user folder instead. An example implementation of this would be [Settings Sync](https://github.com/shanalikhan/code-settings-sync). This extension syncs VSCode settings through GitHub Gists.

As described in the [wiki](https://github.com/shanalikhan/code-settings-sync/wiki/Setup-Guide), the first step is to generate a GitHub personal access token (equivalent to the Sourcery token for this example). After pasting in the token, the extension generates syncLocalSettings.json in the user folder.

Looking at the source code, it seems to be doing something like this:
1. Get path to user folder with [environmentPath.ts](https://github.com/shanalikhan/code-settings-sync/blob/master/src/environmentPath.ts)
1. Set up JSON model with [customConfig.model.ts](https://github.com/shanalikhan/code-settings-sync/blob/master/src/models/customConfig.model.ts)
1. Create the settings file and store settings with [commons.ts SetCustomSettings](https://github.com/shanalikhan/code-settings-sync/blob/master/src/commons.ts#L155)
1. Authenticate with [github.oauth.service.ts](https://github.com/shanalikhan/code-settings-sync/blob/master/src/service/github.oauth.service.ts)
1. Perform the sync with [sync.ts](https://github.com/shanalikhan/code-settings-sync/blob/master/src/sync.ts)

Another example is the [GitHub Pull Requests extension](https://github.com/Microsoft/vscode-pull-request-github/wiki). They had a similar situation, in which they were storing tokens in settings.json, and they now store the local token in a separate encrypted location.

**Comment by br3ndonland** [comment]
VSCode 1.53 introduced a [secrets API](https://code.visualstudio.com/updates/v1_53#_secrets-api) that may be helpful.

**Comment by brendanator** [comment]
This is now done. You can login in directly by running `Sourcery: login` from the command palette
