### ISSUE TITLE
Sourcery only providing suggestions in Windows when run as administrator

### ISSUE THREAD

**Issue by Hellebore** [sourcery-ai/sourcery-vscode#19]
I don't get code suggestions on VS Code for Windows unless I run as administrator? It is running as expected on VS Code for macOS, though.

**Comment by thecesrom** [comment]
**Sourcery** 
**Version**: 0.3.0
___
**Windows**
**Edition**: Windows 10 Enterprise
**Version**: 1909
**OS Build**: 18363.900

**Visual Studio Code**
**Version**: 1.46.1 (user setup)
**Commit**: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
**Date**: 2020-06-17T21:13:20.174Z
**Electron**: 7.3.1
**Chrome**: 78.0.3904.130
**Node.js:** 12.8.1
**V8**: 7.8.279.23-electron.0
**OS**: Windows_NT x64 10.0.18363
___
**macOS**
**Edition**: macOS Catalina
**Version**: 10.15.5

**Visual Studio Code**
**Version**: 1.46.1
**Commit**: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
**Date**: 2020-06-17T21:13:20.174Z
**Electron**: 7.3.1
**Chrome**: 78.0.3904.130
**Node.js:** 12.8.1
**V8**: 7.8.279.23-electron.0
**OS**: Darwin x64 19.5.0
___
Screenshots:
Windows (non-admin)
![vscode-windows](https://user-images.githubusercontent.com/19418023/86192268-05346200-bafe-11ea-9762-6088c5e79eea.png)
Windows (admin)
![vscode-windows-admin](https://user-images.githubusercontent.com/19418023/86192275-082f5280-bafe-11ea-8f43-31d6d4c98b6d.png)
macOS
![vscode-macos](https://user-images.githubusercontent.com/19418023/86192283-0b2a4300-bafe-11ea-84e3-485a9189db9b.png)

**Comment by Hellebore** [comment]
This is strange - can only reproduce it if I explicitly remove my non-administrator user privileges from the sourcery binary.

Are there any error messages shown in the output pane?

One thing to try is to go to %USERPROFILE%\. vscode\extensions and delete the sourcery folder there, then restart vscode as a non-admin and re-install the plugin

**Comment by thecesrom** [comment]
There are no error messages in the Output pane.

Tried your suggestion of removing Sourcery from the extensions, and reinstall, but that didn't fix it. I also installed Visual Studio Code using the System Installer, as I had installed it using the User Installer, and same behavior.

I have verified my user account has Full Control over the sourcery.exe file, so I'm not sure what the issue is.

I wish I could help find the root cause, so please let me know if there's something else I should try.

Thanks!

**Comment by Hellebore** [comment]
Thanks for your help! 

Could you try opening the folder with the exe in the command prompt and running 'sourcery.exe --version'?

**Comment by thecesrom** [comment]
Sure thing.
```bash
$ sourcery.exe --version
> sourcery, version 0.7.4
```

**Comment by Hellebore** [comment]
oh I was really expecting that not to work!
We've just added a new option as well to check the binary can verify your token and do a refactoring -
could you try 'sourcery.exe --verify' please?

**Comment by thecesrom** [comment]
This is the result:

```bash
C:\Users\thecesrom\.vscode\extensions\sourcery.sourcery-0.3.0\binaries\sourcery-0.7.4-win>sourcery.exe --verify
sourcery, version 0.7.4

Verifying server availability https://api.sourcery.ai/health - success
Verifying refactoring functionality - failure
- Incorrect hash value for static hashes
```

But I get the same for the PyCharm plugin, which it is working fine on my computer.

```bash
C:\Users\thecesrom\AppData\Roaming\JetBrains\PyCharmCE2020.1\plugins\sourcery\lib\win>sourcery.exe --verify
sourcery, version 0.7.3

Verifying server availability https://api.sourcery.ai/health - success
Verifying refactoring functionality - failure
- Incorrect hash value for static hashes
```

**Comment by thecesrom** [comment]
This is the output I get on macOS:

```bash
thecesrom@Cesars-MacBook-Air sourcery-0.7.4-mac % ./sourcery --verify 
sourcery, version 0.7.4

Verifying server availability https://api.sourcery.ai/health - success
Verifying refactoring functionality - success
```

**Comment by thecesrom** [comment]
Additional findings.

Sourcery on VSCode for Windows does not provide hints when a single file is opened, but it does on macOS.

Sourcery on VSCode for Windows **does** provide hints when the file is part of a project/workspace.

**Comment by Hellebore** [comment]
Ah ha! Thanks very much that should be helpful in tracking it down.

**Comment by Hellebore** [comment]
Still can't quite reproduce this, which is frustrating! 

Could you give an idea of the directory structure where you're opening a file and not getting suggestions?
Also the sequence of actions you take would be useful - (e.g. are you opening vscode for a workspace then opening a file outside it, etc)

**Comment by thecesrom** [comment]
I placed a single file on the Desktop (`C:\Users\{user}\Desktop`).

Steps to reproduce:

1. Right-click on the file
2. Click on "Open with Code"

File: `sourcery.py`
Code:
```python
def fruit_love(loves_oranges):
    if loves_oranges:
        print('I love oranges')
        print('I love fruit')
    else:
        print('I love fruit')


def test(option: int):
    if option == 1:
        print(1/0)
    elif option == 2:
        d = {'a': 1}
        print(d['c'])
    else:
        pass

```

The only way I get hints is when the file is under source control.

I have created a workspace that is not under source control, and I get no hints at all.

**Comment by Hellebore** [comment]
@thecesrom sorry it's been quite a while! Is this still happening with our latest version?

**Comment by thecesrom** [comment]
Hello, @Hellebore. I can happily report that I recreated the `sourcery.py` file on my Desktop and with version `0.10.2` everything is working  fine, and I do get code refactorings from Sourcery.

Thanks for the follow-up!
