### ISSUE TITLE
Add token reset

### ISSUE THREAD

**Issue by br3ndonland** [sourcery-ai/sourcery-vscode#20]
As mentioned in sourcery-ai/sourcery-vscode#18, many people store their _settings.json_ in public GitHub repos or Gists. Their Sourcery tokens could be accidentally compromised if pushed to a public repo or Gist.

If a token is compromised, the user should be able to deactivate the token and activate a new one.

Relates to sourcery-ai/sourcery#46.

**Comment by brendanator** [comment]
Good suggestion, thanks

**Comment by brendanator** [comment]
This is now available on the website - https://sourcery.ai/download/

**Comment by br3ndonland** [comment]
Thank you. I tried out the token reset and it works well for me.
