### ISSUE TITLE
Sourcery stopped working, cannot click Enable button in side bar

### ISSUE THREAD

**Issue by Teleshot** [sourcery-ai/sourcery-vscode#203]
I was using Sourcery in VS Code a few days ago and it was working perfectly.  Today I opened VS Code and noticed it wasn't working any more as it is not even giving suggestions in the "welcome-to-sourcery" file. If I try to click on the blue Enable button in the side bar it doesn't do anything or provide any message/feedback. Tabbing to the button and pressing the Enter key is the same result. 

![Code_VZShJ2WMIQ](https://github.com/sourcery-ai/sourcery-vscode/assets/489790/a621f967-97c1-4968-bfe6-f39a4465b282)

OS: Windows 10 Version 22H2 (OS Build 19045.3324)
Sourcery version 1.7.0
VS Code version 1.81.1

Sourcery Log file:
[sourcery.log](https://github.com/sourcery-ai/sourcery-vscode/files/12359531/sourcery.log)

### Steps I have tried:

- Restarting VS Code
- Uninstall and reinstall Sourcery extension
- Searching and deleting sourcery.yaml / auth.yaml files on my system and logging into Sourcery in VS Code via browser again

**Comment by brendanator** [comment]
This is now released and should be fixed
