### ISSUE TITLE
possible Memory Leak?

### ISSUE THREAD

**Issue by Giddius** [sourcery-ai/sourcery-vscode#27]
Been noticing that while having Vscode with sourcery enable open for some time (>2hrs) no matter if code is executed or not, that sorcery starts to consume more and more memory. This behaviour is worsend by having multiple windows of Vscode open and completely goes away when disabling Sourcery.

Worst case was:
windows 10 x64
runtime: >24hrs
Vscode windows 4
Sourcery Memory usage >14gb

I also had an discord bot run for a few hours that reported overall memory usage as an plot a few times and will provide said plot when I have a fresh instance of it.

**Comment by Hellebore** [comment]
Thanks for the report! We're investigating and will try and release a fix as soon as we can.

**Comment by Giddius** [comment]
![memorygraph](https://user-images.githubusercontent.com/60372374/104462616-1aac3d80-55b1-11eb-8d29-9dfbac8eea9a.png)
![sourcery_memory](https://user-images.githubusercontent.com/60372374/104462617-1b44d400-55b1-11eb-94ff-e5fcfdbe8a37.png)


said graph and current consumption.

4 Vscode windows

**Comment by Hellebore** [comment]
We've just released 0.8.7 which should improve memory consumption. Would you be able to give it another test?
