### ISSUE TITLE
Sourcery prompts for my token on startup every-time

### ISSUE THREAD

**Issue by tekumara** [sourcery-ai/sourcery-vscode#34]
Despite having supplied it already.

sourcery v0.8.8

**Comment by Hellebore** [comment]
Oh dear! Sorry about this.

Could you please let me know which OS and VS Code version you're on? Also what does it show in the Preferences > Settings if you search for `sourcery`?

**Comment by tekumara** [comment]
Version: 1.55.0
Commit: c185983a683d14c396952dd432459097bc7f757f
Date: 2021-03-30T16:01:05.981Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

Preferences > Settings -> Sourcery: Token was empty and wouldn't keep my token even when I entered it.

I tried uninstalling and reinstalling. Seems to be working now.
