### ISSUE TITLE
Option to disable low code quality globally

### ISSUE THREAD

**Issue by Stanzilla** [sourcery-ai/sourcery-vscode#44]
Hey there! I was wondering if it would be possible to disable the low code quality warnings globally, or at least per workspace?

**Comment by Hellebore** [comment]
You can set up `.sourcery.yaml` config files per workspace where you can configure the threshold for showing the low code quality warnings. Setting it to 0 ought to disable them altogether. See here for details:
https://docs.sourcery.ai/Configuration/
