### ISSUE TITLE
sourcery on arm64 devcontainers

### ISSUE THREAD

**Issue by ngam** [sourcery-ai/sourcery-vscode#46]
Usually the sourcery extension fails in in some arm64 containers. For example, I get the following error from a basic python container that defaults to arm64 linux with the following Dockerfile,

```Dockerfile
ARG VARIANT="3"
FROM mcr.microsoft.com/vscode/devcontainers/python:0-${VARIANT}
```

and the error,

```bash
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
[Info  - 7:09:46 PM] Connection to server got closed. Server will restart.
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
[Info  - 7:09:46 PM] Connection to server got closed. Server will restart.
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
[Info  - 7:09:46 PM] Connection to server got closed. Server will restart.
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
[Info  - 7:09:46 PM] Connection to server got closed. Server will restart.
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
[Error - 7:09:46 PM] Connection to server got closed. Server will not be restarted.
```

which basically means sourcery doesn't work inside the devcontainer.

**Comment by ngam** [comment]
More details:

```
The /home/vscode/.vscode-server/extensions/sourcery.sourcery-0.9.6/sourcery_binaries/install/linux/sourcery server crashed 5 times in the last 3 minutes. The server will not be restarted.
```

<img width="733" alt="Screen Shot 2021-11-09 at 23 07 43" src="https://user-images.githubusercontent.com/67342040/141047994-dba77f66-495a-4d50-815b-f60250029d6f.png">

**Comment by ngam** [comment]
This is likely the trigger: https://github.com/sourcery-ai/sourcery-vscode/blob/8147cf9303f83dac246a0ec73ab96ea4035d8d57/src/executable.ts#L24

**Comment by ngam** [comment]
Also, fwiw, sourcery still runs via rosetta on osx-arm64...

**Comment by Hellebore** [comment]
Thanks for raising this! Yes that does look like the issue.
Have you got a link for setting up an ARM 64 devcontainer so I can test this?

**Comment by ngam** [comment]
could you try the python one with `-bullseye`? See [here]( https://github.com/microsoft/vscode-dev-containers/blob/19adbac72304efc3f7b09970a3bac3c5a68a4c27/containers/python-3/.devcontainer/Dockerfile#L1-L3)

**Comment by ngam** [comment]
@Hellebore any update on this or any potential for a solution soon? Closing otherwise.
