### ISSUE TITLE
Possible Issue? On Apple Silicon M1 Max, the sourcery extension cannot start

### ISSUE THREAD

**Issue by simkimsia** [sourcery-ai/sourcery-vscode#48]
i am getting this error

![image](https://user-images.githubusercontent.com/245021/143809658-1f98094d-b3a1-45bd-a902-ffeb733c3894.png)

Can advise?

**Comment by ngam** [comment]
@Hellebore this should be okay with Rosetta. Find whatever the command to install Rosetta is.

**Comment by ngam** [comment]
`/usr/sbin/softwareupdate --install-rosetta --agree-to-license`

**Comment by Hellebore** [comment]
@simkimsia could you try running the above command and see if that resolves the issue?
