### ISSUE TITLE
for i in range(0,10)[::-1] changes to for i in range(10)[-1]

### ISSUE THREAD

**Issue by Clusks** [sourcery-ai/sourcery-vscode#6]
If you have the following code which goes backwards through a range in an unpythonic way:

`for i in range(0,10)[::-1]:  
        print(i)`

Sourcery will recommend changing it to:

`for i in range(10)[-1]:  
       print(i)`

This will result in breaking the code. with the error message:

`TypeError: 'int' object is not iterable`

Ideally, it should be altering the arguments to take advantage of the range step parameter, and the way to recreate the original functionality utilising the step parameter is:

`for i in range(9,-1,-1):
    print(i)`

**Comment by Hellebore** [comment]
Have identified a fix for the issue which will be in our next release.

**Comment by Hellebore** [comment]
Now resolved with release of version 0.2.2 of plugin.
