### ISSUE TITLE
Configurable context menu items

### ISSUE THREAD

**Issue by Antyos** [sourcery-ai/sourcery-vscode#60]
I work in other languages besides Python, so it would be nice to not have the **Sourcery Scan** context menu item pop up on files that it doesn't make sense for, or not at all.

![image](https://user-images.githubusercontent.com/17516195/147887929-d0265a8f-99b6-4dfa-a920-0c73341ca07b.png)

You can add a [when clause](https://code.visualstudio.com/api/references/when-clause-contexts) to choose when certain menu items are available. Noteworthy contexts include:
- `resourceLangId`: Language ID of the selected item
- `config.[configurationOption]`: Allows direct access to a user's settings.

**Comment by Hellebore** [comment]
Ah interesting - thanks for pointing those out.

**Comment by Hellebore** [comment]
Restricted the scan option to Python files and folders.
