### ISSUE TITLE
Empty field added to all pop-ups in Python

### ISSUE THREAD

**Issue by MicaelJarniac** [sourcery-ai/sourcery-vscode#66]
The Sourcery extension adds an empty field on hover pop-ups for all items that don't have metrics to display, even comments:

![image](https://user-images.githubusercontent.com/19514231/152406366-b4471af6-32ef-4cde-87d6-70c2bf230a18.png)
![image](https://user-images.githubusercontent.com/19514231/152406384-d2c18519-9345-4513-bf6b-6946f44c2443.png)
![image](https://user-images.githubusercontent.com/19514231/152406408-b297c27b-cf0b-411e-9e98-df1cda227d11.png)
![image](https://user-images.githubusercontent.com/19514231/152406422-34d271b3-c4f5-49b2-9ef1-fedcd0d11e4a.png)
![image](https://user-images.githubusercontent.com/19514231/152407410-985c2ea3-530f-4221-a60c-db688f751f65.png)
![image](https://user-images.githubusercontent.com/19514231/152406450-4850c2ae-c00d-4b29-88b9-6bcda4b105b9.png)
![image](https://user-images.githubusercontent.com/19514231/152406494-3fe7b7ee-a3b6-47bc-8957-2eb701d24660.png)

---

Sourcery Extension - `v0.10.1`
VS Code:

> Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:39:46.686Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.15.16-1-MANJARO snap

**Comment by Hellebore** [comment]
oh no! Thanks for spotting and raising this!

**Comment by Hellebore** [comment]
Fixed with 0.10.2
