### ISSUE TITLE
Scan for Refactorings command ignores .ipynb files

### ISSUE THREAD

**Issue by angrycaptain19** [sourcery-ai/sourcery-vscode#74]
If you run the Scan for Refactorings command on a folder containing a notebook file or directly on a notebook file it will ignore the notebook file and not return any refactorings, even when they are present

**Comment by reka** [comment]
Hi,

It's an inconsistent user experience indeed:

* Sourcery shows recommendations in VSCode for Jupyter notebooks
* but the `scan` command ignores those notebooks

Supporting notebooks will require some more development work.
I've created an internal project for it. Let's continue the discussion there.
