### ISSUE TITLE
Sourcery also scanning the .git directory

### ISSUE THREAD

**Issue by jdonnerstag** [sourcery-ai/sourcery-vscode#9]
Seems that sourcery is simply scanning all directories. May be sourcery should leverage .gitignore and .git if present.  I'm using VS Code as editor. 
is there, today, a way to tell sourcery which directory to include?

**Comment by Hellebore** [comment]
There isn't at the moment, but we are planning on adding that configuration in the next few weeks.

**Comment by simmol** [comment]
Hey @Hellebore what is the status of this configuration option ?  

I like some of the suggestions sorcery give but i don't want to be suggested changes in files i can not change like in `.venv/lib/side-packages/`

**Comment by Hellebore** [comment]
Hi - sorry for the delay. 
This configuration is now available via a .sourcery.yaml file which has an ignore option.
This is already released but as yet undocumented - will be adding the documentation to our site in the next few days and will post here when ready.

**Comment by Hellebore** [comment]
This new configuration is documented here:

https://github.com/sourcery-ai/sourcery/wiki/Sourcery-configuration
